### ISSUE TITLE
Hello, author, I have a question about testing.

### ISSUE THREAD

**Issue by nuist-xinyu** [ruinmessi/RFBNet#109]
iI use my own dataset to train, but when testing, the test results report this error.

m_detect: 1/871 3.097s 0.001s
im_detect: 21/871 0.025s 0.001s
im_detect: 41/871 0.026s 0.001s
im_detect: 61/871 0.023s 0.001s
im_detect: 81/871 0.026s 0.001s
im_detect: 101/871 0.027s 0.001s
im_detect: 121/871 0.026s 0.002s
im_detect: 141/871 0.022s 0.001s
im_detect: 161/871 0.021s 0.001s
im_detect: 181/871 0.021s 0.001s
im_detect: 201/871 0.022s 0.001s
im_detect: 221/871 0.028s 0.001s
im_detect: 241/871 0.026s 0.001s
im_detect: 261/871 0.021s 0.001s
im_detect: 281/871 0.022s 0.001s
im_detect: 301/871 0.027s 0.002s
im_detect: 321/871 0.027s 0.002s
im_detect: 341/871 0.027s 0.001s
im_detect: 361/871 0.033s 0.002s
im_detect: 381/871 0.021s 0.001s
im_detect: 401/871 0.030s 0.002s
im_detect: 421/871 0.021s 0.001s
im_detect: 441/871 0.028s 0.002s
im_detect: 461/871 0.023s 0.001s
im_detect: 481/871 0.023s 0.001s
im_detect: 501/871 0.021s 0.001s
im_detect: 521/871 0.032s 0.002s
im_detect: 541/871 0.022s 0.001s
im_detect: 561/871 0.024s 0.001s
im_detect: 581/871 0.022s 0.001s
im_detect: 601/871 0.036s 0.002s
im_detect: 621/871 0.021s 0.001s
im_detect: 641/871 0.022s 0.001s
im_detect: 661/871 0.032s 0.002s
im_detect: 681/871 0.026s 0.001s
im_detect: 701/871 0.021s 0.001s
im_detect: 721/871 0.023s 0.001s
im_detect: 741/871 0.022s 0.001s
im_detect: 761/871 0.036s 0.002s
im_detect: 781/871 0.021s 0.001s
im_detect: 801/871 0.031s 0.002s
im_detect: 821/871 0.032s 0.003s
im_detect: 841/871 0.022s 0.000s
im_detect: 861/871 0.022s 0.001s
Evaluating detections
Writing vehicle VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "test_RFB.py", line 190, in <module>
    top_k, thresh=0.01)
  File "test_RFB.py", line 143, in test_net
    testset.evaluate_detections(all_boxes, save_folder)
  File "/home/xinyu/RFBNet-master/data/voc0712.py", line 249, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/xinyu/RFBNet-master/data/voc0712.py", line 306, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/xinyu/RFBNet-master/data/voc_eval.py", line 130, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '00010252'

**Comment by Damon2019** [comment]
hi,have you solved this problem
