### ISSUE TITLE
the problem of test

### ISSUE THREAD

**Issue by StellaGAN** [ruinmessi/RFBNet#122]
$ python test_RFB.py -d VOC -v RFB_vgg -s 300 --trained_model /path/to/model/weights
Traceback (most recent call last):
  File "test_RFB.py", line 157, in <module>
    state_dict = torch.load(args.trained_model)
  File "/home/d302/anaconda3/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/model/weights'
(would you tell me how to slove this testing problem?)

**Comment by Damon2019** [comment]
You should specify the path to the model
for example:
`python test_RFB.py -d VOC -v RFB_vgg -s 300 -m output/RFB_vgg_VOC_epoches_100.pth`
