### ISSUE TITLE
from .nms.gpu_nms import gpu_nms ModuleNotFoundError: 

### ISSUE THREAD

**Issue by liye228** [ruinmessi/RFBNet#16]
Hi !
I could not run train_test.py. 
File "/media/ubuntue/extdisk1/liye/RFBNet-master/utils/nms_wrapper.py", line 9, in <module>
    from .nms.gpu_nms import gpu_nms
ModuleNotFoundError: No module named 'utils.nms.gpu_nms'

why?
can you help me?

**Comment by ruinmessi** [comment]
@liye228 what is your version of gcc and cython?

**Comment by liye228** [comment]
hello!
@ruinmessi 
I have solved the problem I have mentioned.
But now, I get another problem!
It is that I use your code and your model (RFB_mobile_20_7.pth) to generate the 2015 test-dev result. (for  coco). Then I change the results' name and submit it to COCO 2017test-dev but submit failed!
The images of 2017test-dev and 2015test-dev are the same, so I think it is ok to submit the result to 2017test-dev.  Can you submit your results to COCO 2017test-dev successfully? 
the error message as follow:
Error: 
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpjZ8joP/run/program/run.py", line 72, in 
    resFile = os.path.join(resDir, resFiles[0])
IndexError: list index out of range

**Comment by liye228** [comment]
can you give me your 2015test-dev result，i want to check my results。thanks ，my email：670816416@qq.com

**Comment by 20143698lhy** [comment]
hello!
@ruinmessi
can you tell me what is your version of gcc and cython?
thanks

**Comment by dodogoffy** [comment]
> Hi !@ruinmessi
> I run the ./make.sh
> but get
> g++ -pthread -shared -B /home/liye/anaconda3/compiler_compat -L/home/liye/anaconda3/lib -Wl,-rpath=/home/liye/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.6/nms/nms_kernel.o build/temp.linux-x86_64-3.6/nms/gpu_nms.o -L/usr/local/cuda-8.0/lib64 -L/home/liye/anaconda3/lib -R/usr/local/cuda-8.0/lib64 -lcudart -lpython3.6m -o /media/ubuntue/extdisk1/liye/RFBNet-master/utils/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so
> g++: error: unrecognized command line option ‘-R’
> error: command 'g++' failed with exit status 1
> 
> why?
> can you help me?
I meet the same problem. And how do you solve it?

**Comment by dodogoffy** [comment]
@liye228  I meet the same problem. 
command 'gcc' failed with exit status 1
And how do you solve it?
