### ISSUE TITLE
RuntimeError: randperm is only implemented for CPU

### ISSUE THREAD

**Issue by zyyhl** [ruinmessi/RFBNet#18]
Traceback (most recent call last):
  File "train_RFB.py", line 253, in <module>
    train()
  File "train_RFB.py", line 189, in train
    shuffle=True, num_workers=args.num_workers, collate_fn=detection_collate))
  File "/home/user/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/home/user/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 247, in __init__
    self._put_indices()
  File "/home/user/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 295, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/user/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 139, in __iter__
    for idx in self.sampler:
  File "/home/user/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 53, in __iter__
    return iter(torch.randperm(len(self.data_source)).tolist())
RuntimeError: randperm is only implemented for CPU
I am using torch=0.4, python=2.5, ubuntu=14.04, and I have problems during training.

**Comment by ruinmessi** [comment]
@zyyhl pytorch 0.4 is not compatible at this time

**Comment by wgqlovewzr** [comment]
change something in the python file  torch/utils/data/sampler.py like  following
return iter(torch.randperm(len(self.data_source), device=RandomSampler._cpu).tolist())
