### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by kaishijeng** [ruinmessi/RFBNet#2]
@ruinmessi 

 I like to test your pre-trained model on several  images I have.
Do you have a demo.py code which takes an image name as input and display detection result?

Thanks,

**Comment by ruinmessi** [comment]
Ok, I will update a demo within several days. Since I am a little busy recently, I suggest you refer to test_RFB.py and write on your own. Feel free to PR!

**Comment by kaishijeng** [comment]
@ruinmessi 

I got the following error when I run "python test_RFB.py -d COCO -v RFB_mobile -s 300"

Traceback (most recent call last):
  File "test_RFB_new.py", line 51, in <module>
    from models.RFB_Net_mobile import build_net
  File "/home/fire/2TB/src/RFBNet/models/RFB_Net_mobile.py", line 348
    mbox[str(size)], num_classes), num_classes)
SyntaxError: only named arguments may follow *expression

**Comment by ruinmessi** [comment]
@kaishijeng This is the error only occurred when you use python 2+, We only support python 3+ now.

**Comment by kaishijeng** [comment]
@ruinmessi 

When will demo code be  available?

Thanks,

**Comment by ruinmessi** [comment]
@kaishijeng Emm......m, in progress.....

**Comment by zyyhl** [comment]
@ruinmessi When will demo code be available?thanks

**Comment by hokuto-HIRANO** [comment]
When will demo code be available? Thanks.

**Comment by zhangjunyi1225054736** [comment]
When will demo code be available? Thanks.

**Comment by zhangjunyi1225054736** [comment]
When will demo code be available? Thanks.

**Comment by hokuto-HIRANO** [comment]
I added a demo code to visualize detection results.

-> [hokuto-HIRANO/rfbNet/demo/demo.ipynb](https://github.com/hokuto-HIRANO/rfbNet/blob/master/demo/demo.ipynb)

**Comment by DeepPower** [comment]
@vanlong96tg Hi! I tried your demo.py, but the results is not good.
![figure_1](https://user-images.githubusercontent.com/32128257/48833664-d64cfa80-edb6-11e8-81a3-19c1b32f53df.png)

**Comment by XAB745220zt** [comment]
@ruinmessi Can I use it on Windows

**Comment by nuist-xinyu** [comment]
> I added a demo code to visualize detection results.
> 
> -> [hokuto-HIRANO/rfbNet/demo/demo.ipynb](https://github.com/hokuto-HIRANO/rfbNet/blob/master/demo/demo.ipynb)

can you share your demo.py ? thanks! my email:626673305@qq.com

**Comment by Damon2019** [comment]
@ruinmessi @hokuto-HIRANO  @hokuto-HIRANO  @nuist-xinyu  @XAB745220zt can you share your demo.py ? I really need RFBNet demo.py .thanks! my email:626673305@qq.com

**Comment by huanghekun** [comment]
> 我添加了一个演示代码以可视化检测结果。
> 
> -> [hokuto-HIRANO / rfbNet / demo / demo.ipynb](https://github.com/hokuto-HIRANO/rfbNet/blob/master/demo/demo.ipynb)

Could u share me your RFB demo.py?My Email is  18934727904@163.com
