### ISSUE TITLE
ImportError: cannot import name '_mask'

### ISSUE THREAD

**Issue by LeileiCao** [ruinmessi/RFBNet#36]
Hi, thank you for releasing your code. The idea of this paper is amazing.
I tried to train the model, but I met an error as follows:

python train_RFB.py 
Traceback (most recent call last):
  File "train_RFB.py", line 14, in <module>
    from data import VOCroot, COCOroot, VOC_300, VOC_512, COCO_300, COCO_512, COCO_mobile_300, AnnotationTransform, COCODetection, VOCDetection, detection_collate, BaseTransform, preproc
  File "/data_1/models/RFBNet-master/data/__init__.py", line 3, in <module>
    from .coco import COCODetection
  File "/data_1/models/RFBNet-master/data/coco.py", line 21, in <module>
    from utils.pycocotools.coco import COCO
  File "/data_1/models/RFBNet-master/utils/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/data_1/models/RFBNet-master/utils/pycocotools/mask.py", line 4, in <module>
    from . import _mask
ImportError: cannot import name '_mask'

How can I fix it? Thanks a lot.

**Comment by ruinmessi** [comment]
@LeileiCao Make sure you rum make.sh first and use python3+
