### ISSUE TITLE
Training datasets with 2 classes (with style of pascal voc)

### ISSUE THREAD

**Issue by BestSongEver** [ruinmessi/RFBNet#54]
Thanx for ur excellent work!
I need a little help please. @ruinmessi  @yuyijie1995
I am trying to train RFBNet on a dataset with only 2 classes (with style of pascal voc)
I changed ~/data/voc0712.py like this:
--------------------------------
26 VOC_CLASSES = ( '__background__', # always index 0
 27     'person')
 28 ###    'eroplane', 'bicycle', 'bird', 'boat',
 29 ###    'bottle', 'bus', 'car', 'cat', 'chair',
 30 ###    'cow', 'diningtable', 'dog', 'horse',
 31 ###    'motorbike', 'person', 'pottedplant',
 32 ###    'sheep', 'sofa', 'train', 'tvmonitor')

and I changed train_RFB.py like this:
--------------------------------
82 num_classes = (2, 2)[args.dataset == 'COCO']
 83 ###num_classes = (21, 81)[args.dataset == 'COCO']

But I got an issue like this:
--------------------------------
Loading base network...
Initializing weights...
Loading Dataset...
Training RFB_vgg on VOC0712
Traceback (most recent call last):
  File "train_RFB.py", line 258, in <module>
    train()
  File "train_RFB.py", line 209, in train
    images, targets = next(batch_iterator)
  File "/home/ydm/anaconda2/envs/pytorchyp3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/ydm/anaconda2/envs/pytorchyp3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/ydm/anaconda2/envs/pytorchyp3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/ydm/anaconda2/envs/pytorchyp3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/ydm/project-multiscale/RFBNet-master/data/voc0712.py", line 185, in __getitem__\n    target = self.target_transform(target)\n  File "/home/ydm/project-multiscale/RFBNet-master/data/voc0712.py", line 136, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'car\'\n'

Could u please tell how can I fix this issue?
Thanx again!

**Comment by BestSongEver** [comment]
It‘’s Octo. 22 in 2018. Github crashed today, which caused that  i opened two same issues here.
So i am going to close this one. 
See another one here.  #53
