### ISSUE TITLE
batchsize is 1 but there is still out of memory problem

### ISSUE THREAD

**Issue by yuyijie1995** [ruinmessi/RFBNet#61]
Traceback (most recent call last):
  File "/home/wrc/yuyijie/RFBNet/train_RFB.py", line 138, in <module>
    net.cuda()
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/wrc/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

I have two 1080ti GPU and I want to use the '1'  to train ,then I set os.environ=1 
choose batchsize=1.nw=4 but still this error happened 
what should I do

**Comment by yuyijie1995** [comment]
I can run it in my terminal instead of IDE

**Comment by dodogoffy** [comment]
@yuyijie1995  I have the same problem.
How do you solve it?
