### ISSUE TITLE
error when running test_RFB.py without cuda

### ISSUE THREAD

**Issue by kaishijeng** [ruinmessi/RFBNet#7]
test_RFB.py runs OK when cuda sets as True. However, when I set cuda as False in test_RFB.py and got the following error:

Traceback (most recent call last):
  File "test_RFB.py", line 193, in <module>
    top_k, thresh=0.01)
  File "demo_RFB.py", line 91, in test_net
    out = net(x)      # forward pass
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/topspinn/2TB/src/RFBNet/models/RFB_Net_mobile.py", line 185, in forward
    x = self.base[k](x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 72, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of type Variable[torch.FloatTensor] but found type Variable[torch.cuda.FloatTensor] for argument #1 'weight'

**Comment by ruinmessi** [comment]
@kaishijeng Thanks for reporting this bug. The trained models are stored as cuda Tensor, so you should convert them to float tensor. Use 'net = net.cpu()' after loading models. Meanwhile, the priors is also need to be converted, adding 'priors = priors.cpu()' behind priors.

**Comment by ruinmessi** [comment]
@kaishijeng I've update test_RFB.py now

**Comment by kaishijeng** [comment]
@ruinmessi 
You have the following typo in test_RFB.py
prior = priors.cpu(). 
It should be 
priors = priors.cpu(). 

I am surprised CPU only is so slow. Is this due to pytorch framework? 

Thanks,

**Comment by ruinmessi** [comment]
Thanks! For benchmark of different convolutions, you can see this [repo](https://github.com/yu4u/conv-benchmark)

**Comment by nationalflag** [comment]
When i ran test_RFB.py without cuda, i met the following error:

Traceback (most recent call last):
  File "test_RFB.py", line 12, in <module>
    from data import VOCroot,COCOroot 
  File "/home/nationalflag/disk2/RFBNet/data/__init__.py", line 2, in <module>
    from .coco import COCODetection
  File "/home/nationalflag/disk2/RFBNet/data/coco.py", line 9, in <module>
    from utils.pycocotools.coco import COCO
  File "/home/nationalflag/disk2/RFBNet/utils/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/nationalflag/disk2/RFBNet/utils/pycocotools/mask.py", line 4, in <module>
    from . import _mask
ImportError: cannot import name '_mask'

It seems something wrong with cython?

**Comment by ruinmessi** [comment]
@nationalflag I think it comes from your python version. We currently only support python 3+.  And also make sure you run make.sh first.

**Comment by nationalflag** [comment]
My python version is 3.6, and I have run make.sh actually.

**Comment by ruinmessi** [comment]
@nationalflag I can't reproduce that error.  My Cython version is 0.25.2. Is there any _mask.cpython-*-gpu.so file in your pycocotools/ directory?

**Comment by nationalflag** [comment]
There is a file named _mask.cpython-35m-x86_64-linux-gnu.so

**Comment by ruinmessi** [comment]
@nationalflag  This is a python 3.5 compiled file.

**Comment by nationalflag** [comment]
I figure it out by rerun make.sh in my python 3.6 enviroment. Thanks!
