### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

### ISSUE THREAD

**Issue by zhangbohnu** [ruinmessi/RFBNet#77]
)
  (loc): ModuleList(
    (0): Conv2d(512, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Conv2d(1024, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): Conv2d(512, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): Conv2d(256, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): Conv2d(256, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): Conv2d(256, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (conf): ModuleList(
    (0): Conv2d(512, 126, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Conv2d(1024, 126, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): Conv2d(512, 126, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): Conv2d(256, 126, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): Conv2d(256, 84, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): Conv2d(256, 84, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
)
Loading base network...
Initializing weights...
Loading Dataset...
Training RFB_vgg on VOC0712
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "train_RFB.py", line 257, in <module>
    train()
  File "train_RFB.py", line 220, in train
    out = net(images)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuanfan/pt_object_detection/RFBNet/models/RFB_Net_vgg.py", line 188, in forward
    s = self.Norm(x)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuanfan/pt_object_detection/RFBNet/models/RFB_Net_vgg.py", line 106, in forward
    x0 = self.branch0(x)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuanfan/pt_object_detection/RFBNet/models/RFB_Net_vgg.py", line 21, in forward
    x = self.conv(x)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 24162) is killed by signal: Bus error. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f2f0d4f0160>>
Traceback (most recent call last):
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/data/yuanfan/envs/pytorch_0.4/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by jiangjun001** [comment]
@zhangbohnu I meet the same question.Have you solved this question?

**Comment by DYJNG** [comment]
You can try increase the size of shared memory(shm). The size of shm can see by commond "df -h".
Or you can set "num_works=0" in DataLoder, but it will make train speed slowly.

**Comment by kheffah** [comment]
If you're using docker, I found the solution (and it worked for me at least) [here](https://github.com/ultralytics/yolov3/issues/283). Quoting:
```
"--num-workers 0" will slow down training.
I fixed it by adding "--ipc=host" in my docker container configuration.
```
