### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by rw1995** [ruinmessi/RFBNet#82]
Excuse me, can you help me?
When I follow your steps to run demo（python train_RFB.py -d VOC -v RFB_vgg -s 300 ）， there's a Error
--------------------------------------------------------------------------------------------------------------------
Loading base network...
Initializing weights...
Loading Dataset...
Training RFB_vgg on VOC0712
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=844 error=11 : invalid argument
Traceback (most recent call last):
  File "train_RFB.py", line 257, in <module>
    train()
  File "train_RFB.py", line 220, in train
    out = net(images)
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/RFBNet/models/RFB_Net_vgg.py", line 186, in forward
    x = self.base[k](x)
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:844
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f260fb67470>>
Traceback (most recent call last):
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/csy/anaconda3/envs/pytorch0.4.0/lib/python3.5/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
Connection Refused Error: [Errno 111] Connection refused
----------------------------------------------------------------------------------------------
where is wrong ?
i  use ubuntu 16.04 +cuda9+cudnn v7+anaconda3+python3+

**Comment by rw1995** [comment]
@ruinmessi

**Comment by linshoa** [comment]
I meet this problem in my experiments too, do you have any solution? @rw1995

**Comment by Damon2019** [comment]
@linshoa hi, I meet this problem , do you solved it? thanks
